language: go
go:
- 1.5.1
script:
- go build -o gocollect
deploy:
  provider: packagecloud
  repository: "test"
  username: "dokipen"
  dist: "ubuntu/precise"
  token:
    secure: jHn6ZjrmapibrRvBWvCM0NORsI597EXsVPwl9Z2jnwcPMBFUWiNLCe0NJkTJAK9lIB4Z1hx4YbFKcqMwq9LBYpfwid8EAmTIbKGrOm2xg78E35NISw9QY6TdEX6Dx95dGcO6/m1kIOjvcSEPmrcWjoqN4Q0OFXj9wjcOiZWw4DF1INnPJ3BMPr85JBezLoV1v4YGyBMfFRXazXhEPeHc2NvWA0SDtOf1JdwjeUj2+JbNlO55LmO3LxHKxs6cPzFSKqjsqGzTKeHkezHYHR6k2bw+m5DWGfXX4AhgWvqsHn/BByaqV83uXpak1awFFSUmu1Z8eixvwqTegMVdEev1GxmhjKZ4OBgvFvAklrbDnscrRBLJjCArVWjB7Uwss1bj1N3ricAItJV1vNqo5vF+lNpmUHyYrYgQs4qm4OyYu+B8XSwzyGVpI4ko613B6dTv0N5AhnDVXTXzrsf0hCGbUTp+MlhAH8vUA77Swe1+0SLsMw2cs/+PyHESnh4pJzx6LsAhrsddzeR5UkP6vm+Oy6acRXAREk9gnvR5N7fFgDb616tRVDCvmfbjYK2eQcDI50f4Jjc7eW6HqoLtoRwRXzjBpdpH8pBYtgn7HlP1h+gCSMLJBv8RqcIPDmgunEwEDILruOLim3ExyUKXa6L1P0JKh0KAGvFp52pFO964ShA=
